Feat/view event details
draskonovakovic/front-end pull request #2
Opened 2024-12-03 13:46 UTC by draskonovakovic

This PR includes the following:

View Event Details: Display all information about an event, as well as basic details about the user who created it.
Clicking on an event opens a page showing these details.

@milan-at-2c @ivan-at-2c

2024-12-03 15:06 UTC, igor-at-2c requested changes

2024-12-03 15:06 UTC, igor-at-2c commented on src/lib/user.ts
> +      return response.data.data;
Sta ako je response undefined?

2024-12-03 15:06 UTC, igor-at-2c commented on src/lib/event.ts
> +    return response.data.data;
Sta ako je response undefined?

2024-12-03 15:06 UTC, igor-at-2c commented on src/app/event-details/[id]/page.tsx
> +  const [event, setEvent] = useState<any>(null);
Zasto any?

2024-12-03 15:06 UTC, igor-at-2c commented on src/app/event-details/[id]/page.tsx
> +  const [user, setUser] = useState<any>(null);
Zasto any?

2024-12-03 15:06 UTC, igor-at-2c commented on src/app/event-details/[id]/page.tsx
> +  const [error, setError] = useState<string | null>(null);
Zasto null a ne prazan string?

2024-12-03 15:06 UTC, igor-at-2c commented on src/app/event-details/[id]/page.tsx
> +      const date = new Date(dateString);
Provera da li je data falsy?

2024-12-04 07:10 UTC, draskonovakovic commented on src/app/event-details/[id]/page.tsx
> +  const [event, setEvent] = useState<any>(null);
Zato sto sam budala, zaboravio sam da sam Event tip napravio. Sredicu

2024-12-04 08:31 UTC, igor-at-2c requested changes

2024-12-04 08:31 UTC, igor-at-2c commented on src/app/event-details/[id]/page.tsx
> +      if (eventData.creator_id) {
Bolje uradi early return ako ne postoji creator_id

2024-12-04 08:31 UTC, igor-at-2c commented on src/app/event-details/[id]/page.tsx
> +    if (id) {
Bolje ti je da uradis early return ako ne postoji id

2024-12-04 08:31 UTC, igor-at-2c commented on src/lib/event.ts
> +        console.log(response.data);
Gledaj da brises console.log, nisu ti potrebni na frontu osim ako i dalje testiras neki feature

2024-12-04 09:12 UTC, igor-at-2c approved these changes

2024-12-04 09:13 UTC, merged